project:
  type: website
  output-dir: _site

profile:
  default: french
  group: [french, english]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true
    number-sections: true

execute:
  freeze: auto
