project:
  type: website
  output-dir: _site
  render:
    - "fr/index.qmd"
    - "fr/content/*.qmd"

website:
  title: "Formation Elasticsearch"
  navbar:
    left:
      - text: "Accueil"
        href: index.html
      - text: "Démarrage"
        href: fr/content/getting-started.html
      - text: "Concepts & Architecture"
        href: fr/content/concepts-architecture.html
      - text: "Configuration d'Index"
        href: fr/content/index-configuration.html
      - text: "Langages de Requête"
        href: fr/content/query-languages.html
      - text: "Tableaux de Bord Kibana"
        href: fr/content/kibana-dashboards.html
      - text: "Téléchargements"
        href: fr/content/downloads.html
    right:
      - text: "🇬🇧 English"
        href: "javascript:switchToEnglish()"

  page-footer:
    center: |
      <script>
      function switchToEnglish() {
        const currentPath = window.location.pathname;
        // Replace /fr/ with /en/ in the path
        const newPath = currentPath.replace('/fr/', '/en/');
        window.location.href = newPath;
      }
      </script>

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Introduction"
        contents:
          - fr/index.qmd
          - fr/content/getting-started.qmd
      - section: "Sujets Principaux"
        contents:
          - fr/content/concepts-architecture.qmd
          - fr/content/index-configuration.qmd
          - fr/content/query-languages.qmd
          - fr/content/kibana-dashboards.qmd
      - section: "Ressources"
        contents:
          - fr/content/downloads.qmd
