project:
  type: website
  output-dir: _site

website:
  title: "Elasticsearch Training"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Getting Started"
        href: getting-started.qmd
      - text: "Core Concepts"
        href: core-concepts.qmd
      - text: "Indexing & Documents"
        href: indexing.qmd
      - text: "Search & Queries"
        href: search.qmd
      - text: "Aggregations"
        href: aggregations.qmd
      - text: "Advanced Topics"
        href: advanced.qmd
      - text: "Downloads"
        href: downloads.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Introduction"
        contents:
          - index.qmd
          - getting-started.qmd
      - section: "Fundamentals"
        contents:
          - core-concepts.qmd
          - indexing.qmd
      - section: "Working with Data"
        contents:
          - search.qmd
          - aggregations.qmd
      - section: "Advanced"
        contents:
          - advanced.qmd
      - section: "Resources"
        contents:
          - downloads.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true
    number-sections: true

execute:
  freeze: auto
