project:
  type: website
  output-dir: _site
  render:
    - "en/index.qmd"
    - "en/content/*.qmd"

website:
  title: "Elasticsearch Training"
  navbar:
    left:
      - text: "Home"
        href: en/index.html
      - text: "Getting Started"
        href: en/content/getting-started.html
      - text: "Concepts & Architecture"
        href: en/content/concepts-architecture.html
      - text: "Index Configuration"
        href: en/content/index-configuration.html
      - text: "Query Languages"
        href: en/content/query-languages.html
      - text: "Kibana Dashboards"
        href: en/content/kibana-dashboards.html
      - text: "Downloads"
        href: en/content/downloads.html
    right:
      - text: "🇫🇷 Français"
        href: "javascript:switchToFrench()"

  page-footer:
    center: |
      <script>
      function switchToFrench() {
        const currentPath = window.location.pathname;
        // Replace /en/ with /fr/ in the path
        const newPath = currentPath.replace('/en/', '/fr/');
        window.location.href = newPath;
      }
      </script>

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Introduction"
        contents:
          - en/index.qmd
          - en/content/getting-started.qmd
      - section: "Core Topics"
        contents:
          - en/content/concepts-architecture.qmd
          - en/content/index-configuration.qmd
          - en/content/query-languages.qmd
          - en/content/kibana-dashboards.qmd
      - section: "Resources"
        contents:
          - en/content/downloads.qmd
